// <auto-generated />
using KieuThiHienBTH2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KieuThiHienBTH2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221107171749_Create_Table_Preson")]
    partial class Create_Table_Preson
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("KieuThiHienBTH2.Models.Customer", b =>
                {
                    b.Property<string>("CustomerID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("KieuThiHienBTH2.Models.Preson", b =>
                {
                    b.Property<string>("PresonID")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresonAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PresonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PresonID");

                    b.ToTable("Presons");
                });

            modelBuilder.Entity("KieuThiHienBTH2.Models.Student", b =>
                {
                    b.Property<string>("StudentID")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentID");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
